steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/codecompass-ai:$COMMIT_SHA'
      - '-f'
      - 'deployment/Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/codecompass-ai:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'codecompass-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/codecompass-ai:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MONGODB_URI=${_MONGODB_URI},GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,GITHUB_TOKEN=${_GITHUB_TOKEN}'
      - '--max-instances'
      - '10'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'

images:
  - 'gcr.io/$PROJECT_ID/codecompass-ai:$COMMIT_SHA'

# Environment variables (set these in Cloud Build triggers)
substitutions:
  _MONGODB_URI: 'mongodb+srv://username:password@cluster.mongodb.net/codecompass'
  _GITHUB_TOKEN: 'your-github-token'

timeout: '1200s' 